[project]
name = "experiment-guide"
version = "0.1.0"
description = "Experimental research guide"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax[cuda12]>=0.8.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "optax>=0.2.6",
    "torch>=2.0.0",
]
