[project]
name = "experiment-guide"
version = "0.1.0"
description = "Experimental research guide"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "torch>=2.0.0",
]
